name: Linux

on: [push]

jobs:
  Build-for-Ubuntu:
    name: Build for Ubuntu
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    container:
      image: ubuntu:22.04
    steps:
    - name: install dependencies
      run: |
        apt-get update &&
        apt-get install -y build-essential git

    - name: mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build AmneziaWG tools
      run: |
        make show-env
        make export-env >> $GITHUB_ENV
        make update-version-verbose &&
        cd src &&
        make &&
        mkdir build &&
        cp wg ./build/awg &&
        cp wg-quick/linux.bash ./build/awg-quick

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: ubuntu-22.04-${{ env.OSARCH }}-amneziawg-tools
        path: ./src/build

  Build-for-Alpine:
    name: Build for Alpine
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          #- ubuntu-24.04-arm
    container:
      image: alpine:3.21
    steps:
    - name: install dependencies
      run: apk add linux-headers build-base git

    - name: mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Checkout
      run: |
        git clone ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        git checkout $GITHUB_SHA
#      uses: actions/checkout@v6
#      with:
#        fetch-depth: 0

    - name: Build AmneziaWG tools
      run: |
        make show-env
        make export-env >> $GITHUB_ENV
        make update-version-verbose &&
        cd src &&
        make &&
        mkdir build &&
        cp wg ./build/awg &&
        cp wg-quick/linux.bash ./build/awg-quick

    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:
        name: alpine-3.21-${{ env.OSARCH }}-amneziawg-tools
        path: ./src/build

  GitHub-Release:
    name: GitHub Release
    needs: [Build-for-Ubuntu, Build-for-Alpine]
    strategy:
      matrix:
        include:
          - os: "ubuntu"
            release: "22.04"
          - os: "alpine"
            release: "3.21"
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Calculate checksums
        run: for file in $(find ./${{ matrix.os }}-${{ matrix.release }}-amneziawg-tools/ -type f); do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done
        
      - name: Zip files
        run: zip -r ${{ matrix.os }}-${{ matrix.release }}-amneziawg-tools.zip ${{ matrix.os }}-${{ matrix.release }}-amneziawg-tools

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.os }}-${{ matrix.release }}-amneziawg-tools.zip
          tag: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
